# Generated by Django 4.2.7 on 2025-06-29 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('scene_preset', models.CharField(choices=[('modern_office', 'Modern Office'), ('cozy_lounge', 'Cozy Lounge'), ('outdoor_garden', 'Outdoor Garden')], default='modern_office', max_length=50)),
                ('max_users', models.IntegerField(default=50)),
                ('current_users', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('room_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvatarState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.JSONField(default=dict)),
                ('rotation', models.JSONField(default=dict)),
                ('animation_state', models.CharField(choices=[('idle', 'Idle'), ('walking', 'Walking'), ('typing', 'Typing'), ('waving', 'Waving')], default='idle', max_length=50)),
                ('emotion', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('excited', 'Excited')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'room')},
            },
        ),
    ]
