# Generated by Django 5.2.8 on 2026-03-28 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredits',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProcurementRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('category', models.CharField(blank=True, max_length=200)),
                ('budget_max', models.FloatField(blank=True, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('must_have_features', models.JSONField(default=list)),
                ('compliance_requirements', models.JSONField(default=list)),
                ('current_vendor', models.CharField(blank=True, max_length=200)),
                ('current_spend', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('clones_spawned', models.IntegerField(default=0)),
                ('best_pick', models.CharField(blank=True, max_length=200)),
                ('estimated_savings', models.FloatField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('recommendations', models.JSONField(default=list)),
                ('intelligence', models.JSONField(default=dict)),
                ('processing_time_seconds', models.FloatField(default=0)),
                ('credits_used', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
